plugins {
    id 'com.android.application'
}

android {
    namespace 'ke.co.shopiva.customer'
    compileSdk 36

    defaultConfig {
        applicationId 'ke.co.shopiva.customer'
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
