# Generated by Django 6.1.1 on 2026-09-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_percent",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="promo_text",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
