# Generated by Django 6.1.1 on 2026-09-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_product_discount_percent_product_is_featured_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="product",
            name="stock_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
