# Generated by Django 6.1.1 on 2026-09-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_deliveryagent_order_tracking"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryLocationPing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "longitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "accuracy_meters",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "speed_mps",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "heading_degrees",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_history",
                        to="home.deliveryagent",
                    ),
                ),
            ],
            options={
                "ordering": ("-recorded_at",),
                "indexes": [
                    models.Index(
                        fields=["agent", "-recorded_at"],
                        name="home_deliver_agent_i_6fda9b_idx",
                    ),
                ],
            },
        ),
    ]
